### get customer
GET http://localhost:9999/customers.getById?id=2

### get all customer
GET http://localhost:9999/customers
content-type: application/json
Authorization: Basic admn 1234

### remove customer
GET http://localhost:9999/customers.removeById?id=1

### block customer
POST http://localhost:9999/customers/1/block

### unblock customer
DELETE http://localhost:9999/customers/1/block